### ISSUE TITLE
API: 404 not found 

### ISSUE THREAD

**Issue by huan** [AKAMobi/ibot#11]
以下两个问题：

1、你的文档示例中，端口错误的写成 8080 了。未来请所有的文档和代码更新后，进行自我审查，二次确认。

curl -F uploadFiles=@a -F uploadFiles=@b -F "DATA={\"sender\":\"346786495@qq.com\",\"receiver\":\"wnbupt@qq.com\",\"sendtime\":\"2015-12-16 10:43\",\"subject\":\"测试demo\",\"body\":\"快塞给我一封邮件吧！\"}" http://localhost:8088/IbotInfo/GetInfo  

2、我修改端口为 8088 后，完全不能运行。请绝对避免把不能用的示例，发布给别人。

 curl -F uploadFiles=@a -F uploadFiles=@b -F "DATA={\"sender\":\"346786495@qq.com\",\"receiver\":\"wnbupt@qq.com\",\"sendtime\":\"2015-12-16 10:43\",\"subject\":\"测试demo\",\"body\":\"快塞给我一封邮件吧！\"}" http://localhost:8088/IbotInfo/GetInfo  

<h1>404 Not Found</h1>No context found for request

**Comment by wnbupt** [comment]
fixed #11 and the new temporary address is http://111.207.243.70:8838/SimpleRobot/GetInfo
