### ISSUE TITLE
API Param format

### ISSUE THREAD

**Issue by huan** [AKAMobi/ibot#12]
刚刚试用api，发现你用 form 方法提交了键名为DATA的 json stringify 的数据。

请参照 Freshdesk API 修订成为和他一样的。

**Comment by huan** [comment]
-F DATA={"sender":"346786

把这个 DATA 取消掉。每一个 key 都请用单独的 -F

**Comment by wnbupt** [comment]
fixed #12

**Comment by huan** [comment]
以后你的 issue 提交应该和代码的 commit 关联起来。如果还不会的话，去搜索学习一下。

**Comment by wnbupt** [comment]
好的，之前commit代码时忘记加上fixed issue了。以后会记住的~
